<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9; border-right: 5px solid #20639b; padding: 8px 18px;">
  <h1 style="color:#173f5f; margin-bottom:4px;">نوت‌بوک 15: مبانی Pandas</h1>
  <p><b>سطح:</b> مقدماتی تا متوسط &nbsp; | &nbsp; <b>روش مطالعه:</b> توضیح کوتاه ← اجرای مثال ← تغییر مثال ← حل تمرین</p>
  <h3>هدف‌های یادگیری</h3>
  <ul><li>ساخت Series و DataFrame</li>
<li>بازرسی، انتخاب و فیلتر داده</li>
<li>ساخت ستون و مرتب‌سازی</li>
<li>گروه‌بندی و خلاصه‌سازی اولیه</li></ul>
  <p style="background:#eef6fb; padding:10px; border-radius:8px;">همهٔ سلول‌ها را به‌ترتیب اجرا کنید. برای یادگیری بهتر، مقدار ورودی‌ها را تغییر دهید و نتیجه را پیش‌بینی کنید.</p>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">Series و DataFrame</h2>
  <p>Series یک ستون برچسب‌دار و DataFrame یک جدول با سطر و ستون است. Pandas برای پاک‌سازی و تحلیل دادهٔ جدولی طراحی شده است.</p>
</div>

In [1]:
# Create a DataFrame from records
import pandas as pd

orders = pd.DataFrame([
    {"order_id": 101, "city": "Tehran", "product": "Book", "quantity": 2, "unit_price": 180_000},
    {"order_id": 102, "city": "Shiraz", "product": "Pen", "quantity": 5, "unit_price": 35_000},
    {"order_id": 103, "city": "Tehran", "product": "Bag", "quantity": 1, "unit_price": 950_000},
    {"order_id": 104, "city": "Tabriz", "product": "Book", "quantity": 3, "unit_price": 180_000},
    {"order_id": 105, "city": "Shiraz", "product": "Bag", "quantity": 2, "unit_price": 950_000},
])

orders

   order_id    city product  quantity  unit_price
0       101  Tehran    Book         2      180000
1       102  Shiraz     Pen         5       35000
2       103  Tehran     Bag         1      950000
3       104  Tabriz    Book         3      180000
4       105  Shiraz     Bag         2      950000

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">بازرسی داده</h2>
  <p>پیش از تحلیل، شکل جدول، نوع ستون‌ها و چند ردیف اول را بررسی کنید. این مرحله بسیاری از خطاهای بعدی را آشکار می‌کند.</p>
</div>

In [2]:
# Inspect structure and descriptive statistics
print("Shape:", orders.shape)
print("Columns:", orders.columns.tolist())
print("Data types:\n", orders.dtypes)
orders.select_dtypes(include="number").describe()

Shape: (5, 5)
Columns: ['order_id', 'city', 'product', 'quantity', 'unit_price']
Data types:
 order_id       int64
city          object
product       object
quantity       int64
unit_price     int64
dtype: object

         order_id  quantity     unit_price
count    5.000000  5.000000       5.000000
mean   103.000000  2.600000  459000.000000
std      1.581139  1.516575  452111.711859
min    101.000000  1.000000   35000.000000
25%    102.000000  2.000000  180000.000000
50%    103.000000  2.000000  180000.000000
75%    104.000000  3.000000  950000.000000
max    105.000000  5.000000  950000.000000

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">انتخاب با loc و iloc</h2>
  <p><code>loc</code> برچسب سطر و ستون را می‌گیرد؛ <code>iloc</code> بر اساس جایگاه عددی انتخاب می‌کند.</p>
</div>

In [3]:
# Select columns and rows explicitly
print(orders.loc[:, ["order_id", "city", "product"]])
print(orders.iloc[:3, :2])

   order_id    city product
0       101  Tehran    Book
1       102  Shiraz     Pen
2       103  Tehran     Bag
3       104  Tabriz    Book
4       105  Shiraz     Bag
   order_id    city
0       101  Tehran
1       102  Shiraz
2       103  Tehran

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">فیلتر و ساخت ستون</h2>
  <p>شرط یک Series بولی می‌سازد. برای چند شرط از <code>&</code> و <code>|</code> همراه پرانتز استفاده کنید.</p>
</div>

In [4]:
# Add a calculated column and filter rows
orders = orders.assign(
    total=lambda frame: frame["quantity"] * frame["unit_price"]
)

large_orders = orders[
    (orders["total"] >= 500_000) & (orders["quantity"] >= 1)
]

large_orders.sort_values("total", ascending=False)

   order_id    city product  quantity  unit_price    total
4       105  Shiraz     Bag         2      950000  1900000
2       103  Tehran     Bag         1      950000   950000
3       104  Tabriz    Book         3      180000   540000

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">گروه‌بندی</h2>
  <p><code>groupby</code> داده را به گروه‌ها تقسیم، محاسبه و نتیجه را ترکیب می‌کند. نام‌گذاری خروجی‌ها خوانایی گزارش را بیشتر می‌کند.</p>
</div>

In [5]:
# Aggregate sales by city
city_summary = (
    orders.groupby("city", as_index=False)
    .agg(
        order_count=("order_id", "count"),
        total_sales=("total", "sum"),
        average_order=("total", "mean"),
    )
    .sort_values("total_sales", ascending=False)
)

city_summary

     city  order_count  total_sales  average_order
0  Shiraz            2      2075000      1037500.0
2  Tehran            2      1310000       655000.0
1  Tabriz            1       540000       540000.0

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">تمرین کوتاه</h2>
  <div style="background:#fff7df; border:1px solid #f0c36d; padding:12px; border-radius:8px;">برای هر محصول، تعداد سفارش، مجموع تعداد فروخته‌شده و درآمد کل را محاسبه کنید؛ سپس محصول پردرآمد را مشخص کنید.</div>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">پاسخ پیشنهادی</h2>
  <p>ابتدا پاسخ خودتان را بنویسید؛ سپس این سلول را اجرا و مقایسه کنید.</p>
</div>

In [6]:
# Build a product-level sales report
product_summary = (
    orders.groupby("product", as_index=False)
    .agg(
        order_count=("order_id", "count"),
        units_sold=("quantity", "sum"),
        revenue=("total", "sum"),
    )
    .sort_values("revenue", ascending=False)
)

best_product = product_summary.iloc[0]["product"]
print("Best product:", best_product)
product_summary

Best product: Bag

  product  order_count  units_sold  revenue
0     Bag            2           3  2850000
1    Book            2           5   900000
2     Pen            1           5   175000

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">الگوی کار</h2>
  <p>بازرسی ← انتخاب ستون‌های لازم ← پاک‌سازی ← ساخت ویژگی ← فیلتر ← گروه‌بندی، یک مسیر رایج و قابل اعتماد در تحلیل Pandas است.</p>
</div>